apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: shopping-cart-template
  annotations:
    description: "Shopping Cart Template"

objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: shopping-cart-${APP_ENVIRONMENT}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: shopping-cart-${APP_ENVIRONMENT}
      template:
        metadata:
          labels:
            app: shopping-cart-${APP_ENVIRONMENT}
        spec:
          containers:
            - name: shopping-cart-${APP_ENVIRONMENT}
              image: quay.io/${QUAY_USER_OR_GROUP}/do400-recover:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              env:
                - name: APP_ENVIRONMENT
                  value: "${APP_ENVIRONMENT}"
              ports:
                - containerPort: 8080

  - kind: Service
    apiVersion: v1
    metadata:
      name: shopping-cart-${APP_ENVIRONMENT}
      labels:
        app: shopping-cart-${APP_ENVIRONMENT}
    spec:
      selector:
        app: shopping-cart-${APP_ENVIRONMENT}
      ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: shopping-cart-${APP_ENVIRONMENT}
      labels:
        app: shopping-cart-${APP_ENVIRONMENT}
    spec:
      to:
        kind: Service
        name: shopping-cart-${APP_ENVIRONMENT}
      port:
        targetPort: 8080

parameters:
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: true

  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
    value: "latest"

  - name: APP_ENVIRONMENT
    description: "Environment name"
    required: true
    value: "stage"